ALTER TABLE questions
  MODIFY COLUMN content LONGTEXT NOT NULL,
  MODIFY COLUMN script_text LONGTEXT NULL,
  MODIFY COLUMN explanation LONGTEXT NULL,
  MODIFY COLUMN audio_url TEXT NULL;

ALTER TABLE answers
  MODIFY COLUMN content LONGTEXT NULL;
